---
title: "Quantitative Methods in Life Sciences"
author: "Elizabeth King and Kevin Middleton"
date: "Spring 2023"
output:
  html_document:
    smart: no
    theme: flatly
  pdf_document:
    fig_caption: yes
    fig_height: 3
    fig_width: 6.5
    latex_engine: xelatex
    number_sections: no
geometry: margin=1in
mainfont: Arial
mathfont: Arial
fontsize: 12pt
subtitle: BIO_SC 8640 / PTH_AS 8640
csl: evolution.csl
---


## Course Goals

This is a graduate-level course in statistical analysis designed with the specific needs of students in life sciences, focusing on statistical literacy: performing, interpreting, and writing about biological data analysis. As such, we will assume a basic understanding of some topics and zero understanding of other topics. We will cover most topics broadly and occasionally in great depth, highlighting the perils and pitfalls of different methods, while providing guidelines for a wide array of statistical approaches to data analysis. We will seek to find the balance between really understanding all the math involved and learning to be a competent practitioner and consumer of analysis. We will emphasize the practical over the theoretical, with additional emphasis on the communication of data (plotting, graphs, figures) and of results.

### Guiding idea

> "Science is a way to teach how something gets known, what is not known, to what extent things are known (for nothing is known absolutely), how to handle doubt and uncertainty, what the rules of evidence are, how to think about things so that judgments can be made, how to distinguish truth from fraud, from show..." (Feynman, 1953)

By the end of this course, you will have a foundation in the quantitative methods that are used to answer these fundamental questions of science.

### Background knowledge

**If you have never used R before**, you must attend the pre-course workshop (01/15) to install R on your laptop and work through some Swirl tutorials (http://swirlstats.com/) prior to the first course meeting (01/22).

We will start with the assumption of some very minimal previous exposure to the following topics:

- Basic probability rules
- Kinds of variables (continuous, categorical)
- Basic understanding of distributions: normal (Gaussian), binomial (Bernoulli), $t$, $F$, $\chi^2$
- Estimates of central tendency and spread (mean, median, variance, standard deviation, standard error, confidence intervals, $Z$-scores)
- Tests of group means (and their assumptions)
    - _t_-tests
    - one-way ANOVA
- Bivariate linear regression (and its assumptions)

*You need not be an expert*, but if anything on this list is unfamiliar to you, ask Google for help. A list of online and print resources is provided in Canvas under the "Resources" module.

----

## Course information

### Your Collaborators

Elizabeth King

- kingeg@missouri.edu
- Tucker 401

Kevin Middleton

- middletonk@missouri.edu
- Tucker 222

### Meeting times and place

The course will meet Fridays from 10:00-11:50 in Tucker 322. 

### Expectations

You will get as much or as little from this class as you put into it. Assignments are graded only for completion. You should go through your own answers along with the provided answer key to check. There are many equally correct ways to do many things in R. Your method may differ, but the results should not. Our provided solution methods are just our preferred way.

This course will require you to watch lecture videos outside of class and answer questions related to those videos through Canvas. Treat these online lectures as you would a regular, in-person lecture:

- You should be taking notes.
- You should pause the videos if you need to.
- You may need to re-watch and/or search the internet or the provided resources for additional information.

We expect you to be an active participant in class. If you do not understand something, it is your responsibility to ask. Being a silent attendee will not benefit you, and your instructors will not know if you do not understand until it is too late. We will provide a way to anonymously ask questions via Canvas.

- You must try, be willing to fail, and keep trying. This process is part of learning.
- You must try to learn from your mistakes, so that you will avoid making them again.
- Exhaust your own means and those of your group before asking for help.^[Ask yourself, how would I solve this problem if you were an independent researcher?] Then ask for help.
- Do any readings that are assigned. Be prepared for discussion.
- No mystery numbers are allowed. It should be clear where every number comes from.
- Plot the data. The answer you get from your statistical test should be apparent from thoughtful plots of your data.

If you fail to do the first assignment and/or show up to the first class we reserve the right to drop you from the course to allow someone else to take it.


### Quiz questions

Each set of lecture videos will have associated quiz questions. Complete these before our weekly meeting. These questions are not graded for correctness, only for completion. They will help your instructors guide the discussion during out meetings, so please take these questions seriously.


### Problem sets

Each week you will be randomly assigned to groups to work collaboratively on a problem set. All members of the group should participate, and each group member should submit the same set of answers (i.e., each member should submit the assignment, but these should be identical).

Problem sets will not be graded for correctness, only for completion.

You will fill out a peer evaluation of your group members each week. These evaluations will contribute to your participation grade.


### Progress checks

Following each four week period, we will spend one week reviewing what we have learned and assessing our progress. During these weeks, instead of completing a problem set in a group, you will check your own understanding and progress in the course by completing a progress check independently. *You can not work with other members of the class or anyone else on this assignment*. You will be able to use all other available resources (books, notes, lectures, internet, etc.). Our in-class time this week will be an opportunity to ask questions about any of the material we have covered to that point. 


### Grading

Your grade in the course will be a function of:

1. Quiz questions 
1. Problem sets 
1. Peer evaluations (both your own completion of and others' evaluation of you)
1. In class contributions
1. Progress checks 

----
\newpage


## Schedule

Note that this is a general outline. The schedule of topics is subject to change.

_#_  | _Date_  | _Topic_                          |
-----|---------|----------------------------------|
00   | F 1/13  | Pre-workshop. Installing R, etc. |
01   | F 1/20  | Reproducible research, programming with data |
02   | F 1/27  | Data organization, loading, visualization |
03   | F 2/03  | Tidy data and transformations |
04   | F 2/10  | Probability and distributions |
--   | F 2/17  | Progress Check: Weeks 1-4  |
05   | F 2/24  | Frameworks for inference |
06   | F 3/03  | Central tendency, differences of means, linear regression |
07   | F 3/10  | Parameter estimation |
08   | F 3/17  | Multiple predictors |
--   | F 3/24  | Progress Check: Weeks 5-8  |
09   | F 4/07  | Partitioning variance, multilevel models |
10   | F 4/14  | Model comparison, model-based inference, cross-validation |
11   | F 4/21  | Experimental Design, multiple comparison procedures, power analysis |
12   | F 4/28  | Advanced Data Analysis Topics |
--   | F 5/05  | Progress Check Weeks: 9-12  |


## Course Communication

While we know students are always dealing with a lot, and that has been particularly true the past few years with the global pandemic, adjustment to a lot of remote work, and constant global events that highlight big challenges our society is facing, such as racial injustice and climate change. Our main goal in how we have set up this course is to help you to learn the course material in these challenging circumstances. You should know that we understand that there may be times that your ability to engage with the course is impacted. We will ask in these situations simply that you communicate with us and let us know what is going on. *The more and the earlier, you communicate with us, the more we will be able to help.*

All course material, announcements, and instructions will be available on the course Canvas site. We assume you will check Canvas regularly. We will only communicate with you via Canvas messaging. Please make sure you have checked your notification settings to ensure you receive these messages. You may communicate with us via Canvas messaging or by emailing our university email addresses. 


## Due Dates and Extensions

The lectures, readings, weekly quizzes, weekly assignments, and progress checks all have associated due dates. The benefit of these due dates are that they help you to keep up with the course material. This also allows us to give you feedback and answer keys in a timely fashion. However, if you need more time on one of these, please contact us to let us know (see Course Communication above). If you are having trouble with many due dates, get in touch so we can discuss how to best accommodate the situation.


## Diversity and Inclusion

Excellence in science, including teaching and learning, happens only in diverse and inclusive environments. We can accomplish our goal of an excellent learning outcome only in an inclusive, unbiased and prejudice-free environment that values, respects, and welcomes all individuals with their diverse backgrounds, experiences and perspectives. This requires that everybody be respectful of others in the community (students, faculty, and staff), regardless of their backgrounds. It also requires appreciating that interacting with people of different backgrounds is an opportunity for personal and intellectual growth. We expect everyone in this class to follow the principles laid out in the Diversity Statement of the Division of Biological Sciences (https://biology.missouri.edu/diversity-statement). Please take the time to read the complete statement and understand the expectations.


## Intellectual Pluralism

The University community welcomes intellectual diversity and respects student rights. Students who have questions or concerns regarding the atmosphere in this class (including respect for diverse opinions) may contact the departmental chair or divisional director; the director of the Office of Students Rights and Responsibilities; the MU Equity Office, or equity@missouri.edu.

All students will have the opportunity to submit an anonymous evaluation of the instructor(s) at the end of the course.


## Mental Health

The University of Missouri is committed to supporting student well-being through an integrated network of care, with a wide range of services to help students succeed. The MU Counseling Center offers professional mental health care, and can help you find the best approach to treatment based on your needs. Call to make an appointment at 573-882-6601. Any student in crisis may call or go to the MU Counseling Center between 8:00–-5:00 M-F. After hours phone support is available at 573-882-6601.

Visit our website at https://wellbeing.missouri.edu to take an online mental health screening, find out about workshops and resources that can help you thrive, or learn how to support a friend. Download Sanvello, a phone app that teaches skills and strategies to help you maintain good mental health. Log in with your Mizzou e-mail to unlock all the tools available through Sanvello at no cost to you.


## ADA

Students with Disabilities:

If you anticipate barriers related to the format or requirements of this course, if you have emergency medical information to share with me, or if you need to make arrangements in case the building must be evacuated, please let me know as soon as possible.

If disability related accommodations are necessary (for example, a note taker, extended time on exams, captioning), please register with the MU Disability Center, S5 Memorial Union, 573-882-4696, and then notify me of your eligibility for reasonable accommodations.


## Academic Dishonesty

Academic integrity is fundamental to the activities and principles of a university. All members of the academic community must be confident that each person's work has been responsibly and honorably acquired, developed, and presented. Any effort to gain an advantage not given to all students is dishonest whether or not the effort is successful. The academic community regards breaches of the academic integrity rules as extremely serious matters. Sanctions for such a breach may include academic sanctions from the instructor, including failing the course for any violation, to disciplinary sanctions ranging from probation to expulsion. When in doubt about plagiarism, paraphrasing, quoting, collaboration, or any other form of cheating, consult the course instructor.

Executive Order #38, Academic Inquiry, Course Discussion and Privacy
University of Missouri System Executive Order No. 38 lays out principles regarding the sanctity of classroom discussions at the university. The policy is described fully in section 200.015 of the Collected Rules and Regulations. In this class, students may not make audio or video recordings of course activity, except students permitted to record as an accommodation under section 240.040 of the Collected Rules. All other students who record and/or distribute audio or video recordings of class activity are subject to discipline in accordance with provisions of section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters.

Those students who are permitted to record are not permitted to redistribute audio or video recordings of statements or comments from the course to individuals who are not students in the course without the express permission of the faculty member and of any students who are recorded. Students found to have violated this policy are subject to discipline in accordance with provisions of section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters.
