---
title: 'Analysis of Biological Data'
author: "Kevin Middleton and Elizabeth King"
date: 'Spring 2017'
output:
  pdf_document:
    fig_caption: yes
    fig_height: 3
    fig_width: 6.5
    latex_engine: xelatex
    number_sections: no
  html_document:
    smart: no
    theme: flatly
fontsize: 12pt
geometry: margin=1in
mainfont: Helvetica
mathfont: Helvetica
monofont: Andale Mono
csl: evolution.csl
---

## Course Goals

### Main ideas

### Background knowledge

### Topics we will not cover

----

## Course information

### Meeting times and place

The course will meet Fridays from 1:00-3:00 Tucker FIXME.

### Expectations

### Problem sets

### Review Project

### Grading

----

## Schedule

Note that this is a general outline. The schedule for topics is subject to change.

_#_   | _Date_    | _Topic_                          |
------|-----------|----------------------------------|
00    |           | Pre-workshop. Installing R, etc. |
01    | F 1/20    | Reproducible research, programming with data |
02    | F 1/27    | Data cleaning, organization, visualization |
03    | F 2/03    | Basic probability |
04    | F 2/10    | Likelihood, Bayesian concepts, frequentist framework |
05    | F 2/17    | Example applications of three inference frameworks |
06    | F 2/24    | Parameter estimation, significanace testing |
07    | F 3/03    | Randomization, multiple testing |
08    | F 3/10    | Generalized linear models |
09    | F 3/17    | Generalized linear models |
10    | F 3/24    | Model comparison, model based inference |
11    | F 4/07    | Kinship and phylogenetic methods |
12    | F 4/14    | Multiple comparisons procedures |
13    | F 4/21    | Composite variables |
14    | F 4/28    | Composite variables |
15    | F 5/05    | Experimental design |

Other key dates:

- 4/07 (Friday): Review project paper approval required
- 5/10 (Wednesday): Final exam due
- 5/12 (Friday): Review project due

## Academic Dishonesty

Academic integrity is fundamental to the activities and principles of a university. All members of the academic community must be confident that each person's work has been responsibly and honorably acquired, developed, and presented. Any effort to gain an advantage not given to all students is dishonest whether or not the effort is successful. The academic community regards breaches of the academic integrity rules as extremely serious matters. Sanctions for such a breach may include academic sanctions from the instructor, including failing the course for any violation, to disciplinary sanctions ranging from probation to expulsion. When in doubt about plagiarism, paraphrasing, quoting, collaboration, or any other form of cheating, consult the course instructor.

## Students with disabilities

If you anticipate barriers related to the format or requirements of this course, if you have emergency medical information to share with me, or if you need to make arrangements in case the building must be evacuated, please let me know as soon as possible.

If disability related accommodations are necessary (for example, a note taker, extended time on exams, captioning), please register with the Disability Center (http://disabilitycenter.missouri.edu), S5 Memorial Union, 573-882-4696, and then notify me of your eligibility for reasonable accommodations. For other MU resources for persons with disabilities, click on "Disability Resources" on the MU homepage.

## Intellectual Pluralism

The University community welcomes intellectual diversity and respects student rights. Students who have questions or concerns regarding the atmosphere in this class (including respect for diverse opinions) may contact the departmental chair or divisional director; the director of the Office of Students Rights and Responsibilities; the MU Equity Office, or equity@missouri.edu.

All students will have the opportunity to submit an anonymous evaluation of the instructor(s) at the end of the course.
