---
title: "Introduction"
subtitle: "Quantitative Methods in Life Sciences"
author: 'Elizabeth King and Kevin Middleton'
date: 'Last updated: `r Sys.Date()`'
output:
  ioslides_presentation:
    fig_width: 7
    css: styles.css
csl: evolution.csl
bibliography: Multivariate.bib
---

```{r setup, echo=FALSE}
```

## Notes

None for this lecture.

## Readings

None for this lecture.

## Goals for this course

- Teach you to be an independent, modern scientist
- Be more comfortable with data analysis
    - Data exploration and plotting
- Recipes for analyses
    - Reuse what you have already done
    - Recognize when you can reuse
- Gain experience programming
- Design experiments that can be analyzed before you collect data
- Write about analyses and results
- Interpret what others have done (be good science consumers)

## Goals for *your future as a scientist*

- Teach you to be an independent, modern scientist
- Be more comfortable with data analysis
    - Data exploration and plotting
- Recipes for analyses
    - Reuse what you have already done
    - Recognize when you can reuse
- Gain experience programming
- Design experiments that can be analyzed before you collect data
- Write about analyses and results
- Interpret what others have done (be good science consumers)

## Safe statistics

> "[Statisticians] are at grave risk of becoming irrelevant, not because we are useless, but because we have focussed too much on doing the right thing, rather than doing something that works. As a field, statistics tends to lean towards abstinence based outreach: you should only do statistics if you're in a committed long-term relationship with a professional statistician. If you experiment on your own (or with friends), you will hurt yourself and others. Abstinence based approaches don't work because people will take the risk anyway, and most of the time they will safely enjoy themselves. ... Rather than stigmatizing amateur statistics, we should be doing
out best to provide tools to make it safer." - *Wickham (2015)*

## Why are we teaching this class?

## What you should already know

- A basic understanding of math is necessary (some notation)
    - Calculus-level understanding is not necessary
    - More important: an understanding of what goes into the math

## What you should already know

- General familiarity with some topics:
    - Kinds of variables and their distributions
    - Univariate (means, standard deviations, etc.) and bivariate (correlation, regression, one-way ANOVA) approaches

## What you do not need to know

Programming

- But if you are inexperienced, you *will* need to put in more effort, particularly at the beginning

## What we expect

- Participate
    - In class and in your groups
- Do the readings when applicable
- Do the problem sets conscientiously
- Persistence
    - Be willing to try and fail (and keep on trying)
- Know when to ask for help, and then ask for it
    - Exhaust your own options first (work with your group)
    - "What will I do when I'm on my own?" (Can Google help me?)

## Course outline | Major topics

1. Working with R for reproducible research
1. Data organization and visualization
1. Probability, methods of inference, hypothesis testing
1. Generalized linear models, model comparison
1. Composite variables
1. Experimental design

## Resources

Canvas $\rightarrow$ Modules $\rightarrow$ Pre-course Workshop

- Installing R and RStudio
- Learning R
- Statistics resources

## Quiz 01-1

Go complete quiz 01-1 on Canvas now.

Then move on to lecture 01-2.
