---
title: "Reproducible Research"
subtitle: "Quantitative Methods in Life Sciences"
author: 'Elizabeth King and Kevin Middleton'
date: 'Last updated: `r Sys.Date()`'
output:
  ioslides_presentation:
    fig_width: 7
    css: styles.css
csl: evolution.csl
bibliography: Multivariate.bib
---

```{r setup, echo=FALSE}
```

## Notes

No notes for this lecture

## Readings

Recommended:

- Buffalo (2015) Chapter 1: "How to Learn Bioinformatics"
    - Note: although the focus of this chapter is bioinformatics the rationale applies to any field of life sciences.

## What is reproducible research?

> "By reproducible, I mean that your work can be repeated by other researchers and they can arrive at the same results. For this to be the case, your work must be well documented, and your methods, code, and data all need to be available so that other researchers have the materials to reproduce everything." -VS Buffalo

## Reproducible vs. replicable research

1. Reproducible - Given only 1) the raw data and 2) the scripts (i.e. code), one can produce the same set of results and figures. Not almost the same set, the **SAME SET**.

1. Replicable - Can one repeat the same experiment and reach the same conclusion?

In this class, when we discuss reproducible research, this is what we will mean. Outside of this course, these terms are often used more generally or interchangeably. 

## Problems you are trying to avoid
1. How did I make this figure?
1. Why did I eliminate those data points?
1. Where are the data I eliminated?
1. What analysis did I use to reach this conclusion?
1. I just added new samples. It is going to be so much work to run the analyses again!

## Basic principles

1. Everything via scripts
1. Everything automated with documentation (e.g., comments)
1. Raw data is read only
1. All output reproducible

## Point and click vs. scripting analyses


## Insulating data from analysis

Treat raw data like an endangered species. Don't mess with it!

In data science speak, raw data should always be read-only.
    - /Project
        - /RawData
        - /Data
        - /Scripts
        - /Plots

- Store your data in its rawest form
    - Excel ok
- Do any calculations/analysis elsewhere
    - **No stats or plots in Excel**
    - So many reasons

## Basic tools for reproducible research

1. R
1. Markdown
1. Version control
    - Ok = sequential numbers (never use "final"!)
    - Better = Git (Interested? See [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans))

## Why R for reproducible research?

- Free, now and forever
- Comprehensive and flexible (perhaps too much so for beginners)
- Portable code (Windows, OS X, Unix-like)
- Publication quality plotting
- Encourages good data analysis practices
    - No point and click

## R will become essential for scientists (you, your students)

- As important as Word and Excel
- Learn it now while you have time and energy

## Why not some other statistics package or programming language?

- You probably won't have careers as biostatisticians (SAS, Stata)
- Won't tie to you some non-free software (SAS, SPSS, Systat, Stata, NCSS/PASS, MATLAB)
- Huge data (>$10^6$ observations) is rarely an issue (SAS, Stata, python, julia)
- Speed is rarely an issue for us (fortran, julia, MATLAB, python)
- Python (NumPy/SciPy/pandas/statsmodel) is less mature as a general statistical programming language
- R is open source

## R will make you angry

- Unforgiving
- Opaque
- Often inscrutable errors
    - Learning to deal with errors is critical to reproducibility

## R will make you happy

- Keeps a record of what you did for you
- (Almost) Anything is possible in R
- Beautiful, reproducible plots

## R $\neq$ RStudio

- RStudio is an interface to R
- R can be run without RStudio.
    - The reverse is not true.
- RStudio is one of the most important thing to ever happen to R
- These slides were written in R, using RStudio and R Markdown.

## R Markdown {.smaller}

- Text-based markup language (i.e., HTML)
- Variant of markdown (https://daringfireball.net/projects/markdown/)
- Render to different formats (PDF, HTML, docx)
- Inline R code
    - Your text and analysis coexist together in one file
- Resources
    - http://rmarkdown.rstudio.com/
    - R Markdown Reference Guide: https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
    - http://inundata.org/2012/12/04/how-to-ditch-word/
    - http://moderndata.plot.ly/r-markdown-and-knitr-tutorial-part-1/
    - http://moderndata.plot.ly/r-markdown-and-knitr-tutorial-part-2/

## Reproducibility is an investment for your future self

Doing things “the hard way” now is the easy way in the long run.

Be kind to your future self.

> Your closest collaborator is you six months ago, but you don't reply to emails.

## Quiz 01-2

Go complete quiz 01-2 on Canvas now.

Then move on to lecture 01-3.
