---
title: 'Problem Set 10'
author: "Your Name Here: Group X"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    smart: no
    theme: flatly
    toc: true
    toc_float: true
---

```{r setup, message=FALSE, warning=FALSE}

# This option turn on cacheing of chunks. This will dramatically
# speed up knitting, because only chunks that have changed will
# be recompiled.
knitr::opts_chunk$set(cache = TRUE)
```

## General Framework for This Week's Problem Set

This week we will approach hypothesis testing for several of the models we have fit previously with generalized linear models in a randomization framework. For each, you should:

1. Fit the model to the observed data (feel free to copy your code from original problem set).
1. Decide on a test statistic to use for the randomization.
1. Perform the randomization:
    1. Calculate the test statistic for the *observed* data
    1. Randomly shuffle the observations
    1. Calculate the test statistic for that group
    1. Repeat thousands of times
1. Plot a histogram of the resulting set of test statistics and add a line denoting your observed value
1. Determine the proportion of random combinations resulting in a test statistic more extreme than the observed value ("empirical *P*")

Part of the challenge this week will be figuring out how to implement these steps without step by step guidance, using the tools you've developed so far and the lecture slides  and previous problem sets as a guide. 

Remember to start with a small number of iterations (10 or 100) until you get the code working correctly. Then increase to 10,000 for a final analysis.

## Stalk-eyed flies (PS 05)

Compare the mean eye span on two food sources in stalk-eyed flies. This model is a good candidate for randomization because the variances are likely unequal.

## Earwigs (PS 05)

In PS 05, we studied the proportion of earwigs in a sample that have forceps and associated data on the population density of earwigs. Reanalyze these data.

## Heart Transplant Survivorship (PS 07)

For the data on survivorship after heart transplant, we had to transform the data due to unequal variances. That is not necessary when we use randomization. Reanalyze these data without transformation.

## Bird abundance (PS 07)

We looked at the abundance of bird species in high-altitude "islands" in South America using multiple regression. This is the first model in which we have multiple predictors. In this case, it is usual that you will want to randomize only the outcome variable and retain the associations between the predictors. 

There are four predictors, and you will have 5 randomization tests, though you will fit a single model with multiple predictors to obtain the test statistics for each:

1. The overall multple regression (F-test)
2. Area: "Island" size (thousands of square km)
3. Elevation: Elevation (thousands of meters)
4. Dist_to_Ecuador: Distance to Ecuador (km)
5. Dist_to_Island: Distance to nearest island (km)

You should do the randomization and collect the output test statistics using just one loop.

## Aspirin and cancer (PS 08)

In PS 08, we analyzed whether the odds of cancer differed in women, depending on whether they regularly took a low dose of aspirin. Reanalyze these data using randomization of a generalized linear model. This is more challenging, because you have to decide what test statistic to use. Look at the summary of the "observed" model to try to decide what to use.

## Correlation

Use the bird abundance data above to test for a significant correlation between `Area` and `Elevation`. Again, you have to decide what test statistic to use.
